export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const GET_NUMBERS_CART = "GET_NUMBERS_CART";
export const ADD_CURRENT_USER = "ADD_CURRENT_USER";
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_SUCCESS';

// export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
// export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
